### ISSUE TITLE
[Geplante Wartungsarbeiten] Webseite 19.09.2021 20 Uhr

### ISSUE THREAD

**Issue by Servantur** [gommehdnet/status.gommehd.net#47]
Ab 19.09.2021 gegen 20:00 Uhr werden wir Wartungsarbeiten an unserer Webseite durchführen. Diese werden voraussichtlich zwei Tage andauern. In dieser Zeit wird die Webseite ganz beziehungsweise teilweise nicht zur Verfügung stehen.

**Comment by 4ch3los** [comment]
Die Wartungsarbeiten wurden begonnen.
