### ISSUE TITLE
Netzwerk eingeschränkt verfügbar

### ISSUE THREAD

**Issue by bemoty** [gommehdnet/status.gommehd.net#7]
**26.05.2021 19:13 Uhr** (zuletzt aktualisiert 28.06.2021, 2:45 Uhr)
Nach langer Arbeit und haufenweise Verbesserungen an unserem Hosting ist das Netzwerk ist nun wieder eingeschränkt verfügbar. Vorerst sind nur 5000 Slots auf dem Netzwerk verfügbar. Diese Slots werden wir stetig erhöhen während wir die Last an unsere neue Infrastruktur anpassen. Bitte beachtet, dass es aktuell vereinzelt zu verschiedenen Fehlern in Spielmodi kommen kann. Helft uns diese zu beheben, indem ihr sie mit `/bugreport` an uns meldet.
Vielen Dank für euer Verständnis.

Folgende Einschränkungen wurden behoben:
- Das Ranking in Kit1vs1 bzw. Game1vs1 ist nun wieder verfügbar
- Es kam beim Verbinden vereinzelt zu der Fehlermeldung "Could not contact login servers [..]"
- Es war nicht möglich, im Shop mit Klarna zu zahlen
- Der Verify-Server (verify.gommehd.net) ist nun wieder erreichbar
- In CityBuild gab es Probleme bei der Berechnung von Leveln und Verbindungsprobleme auf manchen Plot- und Farmwelten.
- Die Cloud-Server stehen nun wieder zur Verfügung.
- Der /verify Befehl ist nun wieder vollständig nutzbar.

**26.06.2021 00:50 Uhr**
Guardian ist nun wieder erreichbar.

**23.06.2021 23:52 Uhr**
Keine Statusänderung. Die Einrichtung der Lieferungen geht gut voran und wir hoffen das Minecraft-Netzwerk innerhalb weniger Tage wieder öffentlich zugänglich machen zu können. Vielen Dank für euer Verständnis in dieser schweren Zeit.

**22.06.2021 22:40 Uhr**
Unsere Webseite ist wieder eingeschränkt erreichbar. Einige Teile wie z. B. Guardian, die Clanpages oder Statistiken sind noch nicht verfügbar.

**22.06.2021 1:47 Uhr**
Das Netzwerk ist weiterhin leider nicht erreichbar. Aktuell warten wir auf Antworten von Hosting Providern und auf die Lieferung von Hardware. Unsere Webseite wird vermutlich als erstes wieder online gehen können. Aktuell können wir noch nicht einschätzen, wann das Minecraft Netzwerk wieder vollständig erreichbar sein wird. Alle Ränge werden mindestens um die Dauer des Ausfalls verlängert. Desweiteren werden die täglichen Belohnungen eingefroren. Ihr verliert also nicht eure Streak dadurch, dass aktuell keine Belohnungen abgeholt werden können. Über weitere Updates informieren wir regelmäßig über diese Seite oder auf [Twitter](https://twitter.com/gommehdnet). Unser TeamSpeak steht aktuell mit Einschränkungen zur Verfügung.

**21.06.2021 15:00 Uhr**
Das Netzwerk ist aktuell weiterhin nicht verfügbar. Leider können wir aktuell noch nicht einschätzen, wann wir wieder online gehen können. Wir arbeiten auf Hochtouren an einer Lösung!

**20.06.2021 14:00 Uhr**
Aufgrund von anhaltenden Angriffen ist das Netzwerk aktuell nicht erreichbar.

**Comment by lukalt** [comment]
Siehe #26
